In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [11]:
def gradiente_conjugado(A, b, x0=None, tol=1e-8, max_iter=1000):
    """
    Implementación del método de Gradiente Conjugado para resolver Ax = b.
    
    Parámetros:
    A : ndarray
        Matriz simétrica y definida positiva de tamaño (n, n).
    b : ndarray
        Vector del lado derecho de tamaño (n,).
    x0 : ndarray, opcional
        Estimación inicial de tamaño (n,). Si no se proporciona, se usa un vector de ceros.
    tol : float, opcional
        Tolerancia para el criterio de convergencia.
    max_iter : int, opcional
        Número máximo de iteraciones.
    
    Retorna:
    x : ndarray
        Solución aproximada del sistema Ax = b.
    """
    n = len(b)
    if x0 is None:
        x = np.zeros(n)  # Inicializamos x en ceros
    else:
        x = x0
    
    r = b - A @ x  # Residuo inicial
    p = r.copy()
    rs_old = np.dot(r, r)
    
    for i in range(max_iter):
        Ap = A @ p
        alpha = rs_old / np.dot(p, Ap)  # Paso de actualización
        x += alpha * p
        r -= alpha * Ap  # Nuevo residuo
        rs_new = np.dot(r, r)

        if np.sqrt(rs_new) < tol:  # Verificar convergencia
            break
        
        beta = rs_new / rs_old
        p = r + beta * p  # Actualizar dirección conjugada
        rs_old = rs_new

    return x

A = np.random.randn(4, 4)  # Matriz aleatoria de 4x4

# Hacerla simétrica
A = (A + A.T) / 2

# Hacerla definida positiva sumándole un múltiplo de la identidad
A += 4 * np.eye(4)  # Asegura que todos los autovalores sean positivos

# Imprimir la matriz resultante
print("Matriz simétrica y definida positiva:\n", A)

# Verificar si es definida positiva
eigvals = np.linalg.eigvals(A)
print("Autovalores:", eigvals)
print("¿Es definida positiva?", np.all(eigvals > 0))  # Deben ser todos positivos
# Definir un vector b
b = np.array([1, 2,1,1])

grad = gradiente_conjugado(A, b)

# Imprimir la solución
print("Solución al gradiante conjugado:", grad)

# Verificar si Ax ≈ b
print("Ax:", A @ grad)
print("b:", b)


Matriz simétrica y definida positiva:
 [[ 3.22606894 -0.04526956  0.94154878  0.96329315]
 [-0.04526956  4.51805915  0.25200543  0.44490655]
 [ 0.94154878  0.25200543  2.78534053  1.04737731]
 [ 0.96329315  0.44490655  1.04737731  6.07874976]]
Autovalores: [6.88075856 2.00643989 3.26810979 4.45291014]
¿Es definida positiva? True
Solución al gradiante conjugado: [0.23459284 0.42705216 0.21915533 0.0583149 ]
Ax: [1. 2. 1. 1.]
b: [1 2 1 1]
